# Starter pipeline

trigger:
- master

variables:
  DOCKERHUB_PASSWORD: $(dockerhub_password)

pool:
  vmImage: 'ubuntu-latest'

<<<<<<< HEAD
=======
variables:
  dockerhub_password: $(dockerhub_password)
>>>>>>> 41a76a38a131379ef2d3eb885da2b38a8ce49308
steps:
- script: echo Code
  displayName: 'Code Quality Check'

# Build, Tag and Push the Container to DockerHub
- script: |
    docker build -t infinitemario:latest .
    docker tag infinitemario felipecosta09/infinitemario:latest
<<<<<<< HEAD
    docker login -u felipecosta09 -p $(DOCKERHUB_PASSWORD)
=======
    docker login -u felipecosta09 -p $(dockerhub_password)
>>>>>>> 41a76a38a131379ef2d3eb885da2b38a8ce49308
    docker push felipecosta09/infinitemario:latest
  displayName: 'Container Build, Tag and Push'

# Scan the Container Image using Cloud One Container Security
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Cloud One Container Security Scan'


# Unit Tests
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Unit Tests'

# Deploy to Azure Container Instance
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Deploy to Azure'