# Starter pipeline

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


stages:
  - stage: Code_Quality_Check
    displayName: Code Quality Check
    jobs:
    - job: Code_Quality_Check
      displayName: Static Code Analysis
      steps:
      - script: | 
              echo "SonarQube execution for checkedout code"
        displayName: "SonarQube Code Sanatization Check"

  - stage: Container_Build
    displayName: Container Build, Tag and Push
    jobs:
    - job: Container_Build
      displayName: Container Build, Tag and Push
      steps:
      - script: | 
              echo "Container Build, Tag and Push"
        displayName: "Container Build, Tag and Push"

  - stage: Container_Scan
    displayName: Cloud One Container Security Scan
    jobs:
    - job: Container_Scan
      displayName: Cloud One Container Security Scan
      steps:
      - script: | 
              echo "Cloud One Container Security Scan"
        displayName: "Cloud One Container Security Scan"



# # Build, Tag and Push the Container to DockerHub

# - script: |
#     docker build -t infinitemario:latest .
#     docker tag infinitemario felipecosta09/infinitemario:latest
#     docker login -u felipecosta09 -p $(DOCKERHUB_PASSWORD)
#     docker push felipecosta09/infinitemario:latest
#   displayName: 'Container Build, Tag and Push'
#   env:
#     DOCKERHUB_PASSWORD: $(dockerhub_password)

# # Scan the Container Image using Cloud One Container Security
# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Cloud One Container Security Scan'


# # Unit Tests
# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Unit Tests'

# # Deploy to Azure Container Instance
# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Deploy to Azure'