# Starter pipeline

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Code
  displayName: 'Code Quality Check'

# Build, Tag and Push the Container to DockerHub
- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'infinitemario'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
  displayName: 'Build, Tag and Push'

# Scan the Container Image using Cloud One Container Security
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Cloud One Container Security Scan'


# Unit Tests
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Unit Tests'

# Deploy to Azure Container Instance
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Deploy to Azure'