# Starter pipeline

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Code
  displayName: 'Code Quality Check'

# Build, Tag and Push the Container to DockerHub
- script: |
    docker build -t infinitemario:latest .
  displayName: 'Container Build'

- script: |
    docker tag felipecosta09/infinitemario:latest
    docker login -u $dockerhub_user $dockerhub_password 
    docker push felipecosta09/infinitemario:latest
  displayName: 'Container Tag and Push'

# Scan the Container Image using Cloud One Container Security
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Cloud One Container Security Scan'


# Unit Tests
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Unit Tests'

# Deploy to Azure Container Instance
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Deploy to Azure'