# Starter pipeline

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

# Code Analysis Check
stages:
  - stage: Code_Quality_Check
    displayName: Code Quality Check
    jobs:
    - job: Code_Quality_Check
      displayName: Static Code Analysis
      steps:
      - script: | 
              echo "SonarQube execution for checkedout code"
        displayName: "SonarQube Code Sanatization Check"

# Build, Tag and Push the Container to DockerHub
  - stage: Container_Build
    displayName: Container Build, Tag and Push
    jobs:
    - job: Container_Build
      displayName: Container Build, Tag and Push
      steps:
      - script: | 
          docker build -t infinitemario:latest .
          docker tag infinitemario felipecosta09/infinitemario:latest
          docker login -u $(DOCKERHUB_USERNAME) -p $(DOCKERHUB_PASSWORD)
          docker push felipecosta09/infinitemario:latest
        env:
          DOCKERHUB_PASSWORD: $(DOCKERHUB_PASSWORD)
          DOCKERHUB_USERNAME: $(DOCKERHUB_USERNAME)
        displayName: "Container Build, Tag and Push"

# Scan the Container Image using Cloud One Container Security
  - stage: Container_Scan
    displayName: Cloud One Container Security Scan
    jobs:
    - job: Container_Scan
      displayName: Cloud One Container Security Scan
      steps:
      - script: | 
              docker run deepsecurity/smartcheck-scan-action --image-name=registry.hub.docker.com/felipecosta09/infinitemario:latest --smartcheck-host=$(DSSC_SMARTCHECK_HOST) --smartcheck-user=$(DSSC_SMARTCHECK_USER) --smartcheck-password=$(DSSC_SMARTCHECK_PASSWORD) --image-pull-auth='{"username": "'"$(DOCKERHUB_USERNAME)"'","password": "'"$(DOCKERHUB_PASSWORD)"'"}' --findings-threshold='{"malware": 200, "vulnerabilities": { "defcon1": 200, "critical": 200, "high": 200 }, "contents": { "defcon1": 200, "critical": 200, "high": 200 }, "checklists": { "defcon1": 200, "critical": 200, "high": 200 }}'
        env:
          DSSC_SMARTCHECK_HOST: $(DSSC_SMARTCHECK_HOST)
          DSSC_SMARTCHECK_USER: $(DSSC_SMARTCHECK_USER)
          DSSC_SMARTCHECK_PASSWORD: $(DSSC_SMARTCHECK_PASSWORD)
          DOCKERHUB_USERNAME: $(DOCKERHUB_USERNAME)
          DOCKERHUB_PASSWORD: $(DOCKERHUB_PASSWORD)
        displayName: "Cloud One Container Security Scan"

# Unit Tests
  - stage: Unit_Test
    displayName: Unit Test
    jobs:
    - job: Unit_Test
      displayName: Unit Test
      steps:
      - script: | 
              echo "Unit Test"
        displayName: "Unit Test"


# Deploy to Azure Container Instance
  - stage: Deploy_to_Azure
    displayName: Deploy to Azure Container Instance
    jobs:
    - job: Deploy_to_Azure
      displayName: Deploy to Azure Container Instance
      steps:
      - script: | 
            echo "Deploy to Azure Container Instance"
        displayName: "Deploy to Azure Container Instance"